# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-29 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('AVAIABLE', 'Item can be purchase'), ('RESTOCKING', 'Item will be restock in a few day'), ('SOLD', 'Item Sold out')], max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('AVAIABLE', 'Item can be purchase'), ('RESTOCKING', 'Item will be restock in a few day'), ('SOLD', 'Item Sold out')], max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
