# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-29 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktop',
            name='issue',
            field=models.CharField(default='No issue', max_length=120),
        ),
        migrations.AddField(
            model_name='laptop',
            name='issue',
            field=models.CharField(default='No issue', max_length=120),
        ),
    ]
