# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-30 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('DRINK', 'Drink'), ('FOOD', 'Food'), ('NOODLE', 'Noodle')], max_length=120)),
            ],
        ),
    ]
